# Generated by Django 5.2.4 on 2025-07-24 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=5)),
                ('remark', models.TextField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
