# Generated by Django 5.2.4 on 2025-07-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('profile_pic', models.FileField(default='', upload_to='user_pic/')),
                ('date', models.DateField(default='timezone.now')),
            ],
        ),
    ]
