# Generated by Django 5.2.4 on 2025-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0004_legaladvisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(default='')),
                ('service_pic', models.FileField(default='', upload_to='service_pic/')),
            ],
        ),
    ]
