# Generated by Django 5.2.4 on 2025-07-28 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
