# Generated by Django 5.2.4 on 2025-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0007_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
