# Generated by Django 5.2.4 on 2025-08-06 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0009_leagalservice_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_email', models.CharField(max_length=50)),
                ('document_name', models.CharField(max_length=50)),
                ('document_description', models.TextField()),
                ('document_pic', models.FileField(default='', upload_to='document_file/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legal_app.user')),
            ],
        ),
    ]
