# Generated by Django 5.2.4 on 2025-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0010_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaladvisor',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
